name: Bandit Static Scan

# Customize trigger events based on your DevSecOps process and/or policy
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
            python-version: "3.12.3"
      - name: Install bandit
        run: pip install bandit[sarif]
      - name: Run scan
        run: bandit --ini .bandit2 -f sarif -o /tmp/results.sarif -v || test -f /tmp/results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: /tmp/results.sarif
      - name: upload SARIF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan_central_logs
          path: /tmp/results.sarif
